Semantic release (#74) [skip ci]
* Introduce Semantic Release

* replace dobi with Makefile

diff --git a/.github/workflows/image-workflow.yaml b/.github/workflows/image-workflow.yaml
--- a/.github/workflows/image-workflow.yaml
+++ b/.github/workflows/image-workflow.yaml
@@ -77,7 +77,7 @@ jobs:
     name: Calculate Version
     runs-on: ubuntu-22.04
     outputs:
-      version: ${{ steps.gitversion.outputs.majorMinorPatch }}-${{ steps.gitversion.outputs.commitsSinceVersionSource }}.${{ github.event.pull_request.head.ref }}.${{ steps.shortSha.outputs.shortSha }}
+      version: ${{ steps.version.outputs.version }}
       name_suffix: ${{ steps.eventCheck.outputs.nameSuffix }}
     steps:
       - uses: actions/checkout@v2
@@ -91,17 +91,19 @@ jobs:
         id: gitversion
         uses: gittools/actions/gitversion/execute@v0.9.7
       - name: Get git sha as on PR gitversion provides incorrect sha
-        id: shortSha
+        id: version
         env:
           EVENT_NAME: ${{ github.event_name }}
         run: |
           echo "Github event is a $EVENT_NAME"
           if [ "$EVENT_NAME" = "pull_request" ]; then
-              echo "::set-output name=shortSha::`echo ${{ github.event.pull_request.head.sha }} | cut -c1-8`"
-          elif [ "$EVENT_NAME" = "push" ]; then
-              echo "::set-output name=shortSha::${GITHUB_SHA::8}"
+              sha=`echo ${{ github.event.pull_request.head.sha }} | cut -c1-8`
+              echo "::set-output name=version::${{ github.event.pull_request.head.ref }}-${sha}"
+          elif [ "$EVENT_NAME" = "release" ]; then
+              echo "::set-output name=version::${{ steps.gitversion.outputs.semVer }}"
           else
-              echo "::set-output name=shortSha::invalid"
+              echo "invalid event type ${EVENT_NAME}"
+              exit 1
           fi
       - name: Generate Image name dependend on github event
         id: eventCheck
@@ -110,10 +112,8 @@ jobs:
         run: |
           if [ "$EVENT_NAME" = "pull_request" ]; then
               echo "::set-output name=nameSuffix::-pr"
-          elif [ "$EVENT_NAME" = "push" ]; then
+          elif [ "$EVENT_NAME" = "release" ]; then
               echo "::set-output name=nameSuffix::"
-          else
-              echo "::set-output name=nameSuffix::-invalid"
           fi
 
   dumpversions:
@@ -132,8 +132,8 @@ jobs:
     name: Build and Push Image
     #
     # yocto-runner runs a docker container within the docker:dind image
-    # /yocto-cache is bound to the hosts /yocto-cache directory. 
-    # /downloads /sstate-cache and /install are temporary mounts local for that container. They 
+    # /yocto-cache is bound to the hosts /yocto-cache directory.
+    # /downloads /sstate-cache and /install are temporary mounts local for that container. They
     # survive steps, but are cleared with each new job
     # For details see: https://github.com/ci4rail/public-infrastructure/blob/master/deployment-self-hosted-runners/templates/runnerdeployment.yaml
     #
@@ -163,7 +163,7 @@ jobs:
 
               # clean up after yourself, and release your trap
               rm -f "${{ env.CACHE_LOCKFILE }}"
-              echo cache lock cleared 
+              echo cache lock cleared
               ls /yocto/cache
               trap - INT TERM EXIT
               break
@@ -171,7 +171,7 @@ jobs:
               echo "Cache is locked. Wait"
               sleep 60
             fi
-          done        
+          done
 
       - name: Build Yocto
         env:
@@ -215,7 +215,7 @@ jobs:
               echo "Cache is locked. Wait"
               sleep 60
             fi
-          done        
+          done
 
       - name: Copy TAR artifacts for mender and minio deployment
         if: inputs.output_type == 'tar'
